const fs = require('fs');
const file = 'c:/Users/tua46/OneDrive/Máy tính/DATN_2/QuanLyCongViec/QuanLyCongViec/Frontend/src/components/TaskDetailModal.vue';
let content = fs.readFileSync(file, 'utf8');
const htmlStartStr = '<div class="mb-6 contingency-plans-container" v-else-if="activityTab === \'contingency\'">';
const htmlEndStr = '<div v-else-if="activityTab !== \'contingency\'" class="activity-empty-state">';
const htmlStartIdx = content.indexOf(htmlStartStr);
const htmlEndIdx = content.indexOf(htmlEndStr);
const chunk = content.substring(htmlStartIdx, htmlEndIdx);
console.log('Chunk length:', chunk.length);
console.log('Div open tags:', (chunk.match(/<div/g) || []).length);
console.log('Div close tags:', (chunk.match(/<\/div>/g) || []).length);
